# This rule is not used by the project haproxy-dataplane-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the haproxy.a7d.dev.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: haproxy-dataplane-operator
    app.kubernetes.io/managed-by: kustomize
  name: haproxyacl-editor-role
rules:
- apiGroups:
  - haproxy.a7d.dev
  resources:
  - haproxyacls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - haproxy.a7d.dev
  resources:
  - haproxyacls/status
  verbs:
  - get
