# This rule is not used by the project haproxy-dataplane-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to haproxy.a7d.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: haproxy-dataplane-operator
    app.kubernetes.io/managed-by: kustomize
  name: haproxybackend-viewer-role
rules:
- apiGroups:
  - haproxy.a7d.dev
  resources:
  - haproxybackends
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - haproxy.a7d.dev
  resources:
  - haproxybackends/status
  verbs:
  - get
